// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_R7Ygpp0z5TO2AHLT4Yn-jv3416UWv0',
    appId: '1:977536696355:web:71b47497ad23b6b632f196',
    messagingSenderId: '977536696355',
    projectId: 'sapna-1232a',
    authDomain: 'sapna-1232a.firebaseapp.com',
    storageBucket: 'sapna-1232a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBktM-88sxq-AGbktevfmyxXgkKLRAFuWY',
    appId: '1:977536696355:android:ceecde4530a21f2f32f196',
    messagingSenderId: '977536696355',
    projectId: 'sapna-1232a',
    storageBucket: 'sapna-1232a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjQLLGKexhzPxbIseG4hLC0UWzIme5TVw',
    appId: '1:977536696355:ios:35bcbb33aa49112032f196',
    messagingSenderId: '977536696355',
    projectId: 'sapna-1232a',
    storageBucket: 'sapna-1232a.appspot.com',
    iosBundleId: 'com.example.etc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjQLLGKexhzPxbIseG4hLC0UWzIme5TVw',
    appId: '1:977536696355:ios:aa61152e903ca8e132f196',
    messagingSenderId: '977536696355',
    projectId: 'sapna-1232a',
    storageBucket: 'sapna-1232a.appspot.com',
    iosBundleId: 'com.example.etc.RunnerTests',
  );
}
